spring.application.name=mindtrack_api

# Render asignará un puerto dinámico, si no existe, usa el 8080 localmente
server.port=${PORT:8080}

# Variables de entorno para la base de datos (Render inyectará estos valores)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mindtrack_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}

# Hibernate creará las tablas automáticamente en Render
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect